import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import availableCourses from "./courses";

let sidebars: SidebarsConfig = {};

for (const course of availableCourses) {
  sidebars[`${course.id}Sidebar`] = [
    { type: "autogenerated", dirName: course.id }
  ];
}

export default sidebars;
