name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci 

      - name: Build docusaurus app
        run: npm run build

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy on Railway
        run: railway up --ci --detach
        env:
          RAILWAY_TOKEN: {{ secrets.RAILWAY_TOKEN }}
        working-directory: ./build
