name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Build docusaurus app
        run: npm run build
      - name: Deploy on Railway
        working-directory: ./build
        run: railway up
